FROM rocker/tidyverse:4.1.1

MAINTAINER Matei Teleman (matei.teleman@etu.univ-amu.fr)

# ####################################
# INSTALL JAVA
# ####################################

RUN apt-get update \
&& apt-get -y install openjdk-8-jre \
&& rm -rf /var/lib/apt/lists/*


# ####################################
# INSTALLING R PACKAGES FOR PROJECT
# ####################################

RUN apt-get update && apt-get install -y libxml2-dev \
                                         libhdf5-serial-dev \
                                         python3-pip
RUN apt-get update && apt-get install -y \
  build-essential \
  libglpk40 \
  libx11-dev \
  libxt-dev \
  liblzma-dev \
  libboost-dev \
  libgdal-dev \
  libudunits2-dev \
  libgeos-dev \
  libproj-dev

RUN apt-get install -y libproj-dev libgdal-dev

RUN apt-get install -y libbz2-dev liblzma-dev

RUN /rocker_scripts/install_shiny_server.sh

RUN apt-get update && apt-get install -y libboost-dev
RUN apt-get update && apt-get install -y libboost-all-dev
RUN apt-get install libboost-dev

RUN ln -s /usr/lib/x86_64-linux-gnu/libboost.so.1 /usr/lib/x86_64-linux-gnu/libboost.so
#RUN ln -s /usr/lib/x86_64-linux-gnu/libboost.so.1 /usr/lib/x86_64-linux-gnu/libboost.so


#RUN apt-get install -y aptitude
#RUN aptitude install libboost-dev



RUN R -e "install.packages(c('igraph', 'ggdag'), dependencies = T)"

CMD R -e "source('script/igraph.R')"

# -- Install package managers
RUN R -e 'install.packages( "devtools")'
RUN R -e 'install.packages( "BiocManager")'

# -- Install packages for knitr and markdown
RUN R -e 'install.packages( "knitr")'
RUN R -e 'install.packages( "formatR")'
RUN R -e 'install.packages( "caTools")'
RUN R -e 'install.packages( "rprojroot")'
RUN R -e 'install.packages( "rmarkdown")'
RUN R -e 'install.packages( "shiny")'
RUN R -e 'install.packages( "shinyBS")'
RUN R -e 'install.packages( "shinydashboard")'

# -- Install data analysis tools
RUN apt-get update && apt-get install -y libpng-dev
RUN R -e 'install.packages( "ade4")'
RUN R -e 'install.packages( "png")'
RUN R -e 'install.packages( "data.table")'
RUN R -e 'install.packages( "Rtsne")'
RUN R -e 'install.packages( "spatstat")'
RUN R -e 'install.packages( "Seurat")'
RUN R -e 'install.packages( "umap")'
RUN pip3 install --upgrade --user pip \
    && python3 -m pip install umap-learn

# -- Install Datatable package to have widget tables for reporting
RUN R -e 'devtools::install_github( "ramnathv/htmlwidgets")'
RUN R -e 'install.packages( "DT")'
RUN R -e 'install.packages( "htmltools")'
RUN R -e 'install.packages( "d3heatmap")'

# -- Install plotting tools
RUN R -e 'install.packages( "ggplot2")'
RUN R -e 'install.packages( "ggpubr")'
RUN R -e 'install.packages( "ggrepel")'
RUN R -e 'install.packages( "gplots")'
RUN R -e 'install.packages( "gridExtra")'
RUN R -e 'install.packages( "heatmaply")'
RUN R -e 'BiocManager::install("S4Vectors"); install.packages( "iheatmapr")'
RUN R -e 'install.packages( "igraph")'
RUN R -e 'devtools::install_github( "thomasp85/patchwork")'
RUN R -e 'install.packages( "pheatmap")'
RUN R -e 'install.packages( "reshape")'

# -- Install general prupose libraries
RUN R -e 'install.packages( "funr")'
RUN R -e 'install.packages( "ggalluvial")'
RUN R -e 'install.packages( "pander")'
RUN R -e 'install.packages( "rprojroot")'
RUN R -e 'install.packages( "dplyr")'
RUN R -e 'install.packages( "writexl")'
RUN R -e 'install.packages( "scales")'
RUN R -e 'install.packages( "ggnewscale")'

RUN R -e 'library(BiocManager);install( "limma" )'
RUN R -e 'library(BiocManager);install( "scater" )'
RUN R -e 'library(BiocManager);install( "SC3" )'
RUN R -e 'library(BiocManager);install( "cidr" )'
RUN R -e 'library(BiocManager);install( "clusterProfiler" )'
RUN R -e 'library(BiocManager);install( "pathview" )'
RUN R -e 'library(BiocManager);install( "EnhancedVolcano" )'
RUN R -e 'library(BiocManager);install( "zlibbioc" )'
RUN R -e 'library(BiocManager);install( "grimbough/Rhtslib" )'
RUN R -e 'library(BiocManager);install( "Rsamtools" )'
RUN R -e 'install.packages("NMF")'
RUN R -e 'install.packages("Cairo")'
RUN R -e 'devtools::install_github("jokergoo/circlize")'
RUN R -e 'devtools::install_github("yanlinlin82/ggvenn")'
RUN R -e 'devtools::install_github("jokergoo/ComplexHeatmap")'


RUN R -e 'devtools::install_github("sqjin/CellChat")'
RUN R -e 'devtools::install_github("kevinblighe/EnhancedVolcano")'
RUN R -e 'devtools::install_github("satijalab/seurat-data")'
RUN R -e 'BiocManager::install("pcaMethods")'
RUN R -e 'BiocManager::install("batchelor")'
RUN R -e 'devtools::install_github("cole-trapnell-lab/leidenbase")'
RUN R -e 'devtools::install_github("cole-trapnell-lab/monocle3")'
RUN R -e 'devtools::install_github("velocyto-team/velocyto.R")'




# ####################################
# CLEAN INSTALL
# ####################################
  
RUN apt-get clean\
  && apt-get remove --yes --purge build-essential

RUN mkdir -p /mnt

COPY userconf.sh /etc/cont-init.d/conf

EXPOSE 8787

CMD ["/init"]
